-- object: pms.partners_transaction | type: TABLE --
-- DROP TABLE IF EXISTS pms.partners_transaction CASCADE;

CREATE TABLE pms.partners_transaction (
    id VARCHAR(36) NOT NULL,
    request_dtimes TIMESTAMP NOT NULL,
    response_dtimes TIMESTAMP NOT NULL,
    request_trn_id VARCHAR(64) NOT NULL,
    auth_type_code VARCHAR(128) NULL,
    status_code VARCHAR(36) NULL,
    status_comment VARCHAR(1024) NULL,
    partner_id VARCHAR(36) NOT NULL,
    partner_name VARCHAR(128) NOT NULL,
    entry_type VARCHAR(128) NOT NULL,
    amount NUMERIC NULL,
    cr_by VARCHAR(256) NOT NULL,
    cr_dtimes TIMESTAMP NOT NULL,
    upd_by VARCHAR(256) NULL,
    upd_dtimes TIMESTAMP NULL,
    CONSTRAINT pk_pmstrn_id PRIMARY KEY (id)
);

COMMENT ON TABLE pms.partners_transaction 
IS 'Partners Transaction: Stores transaction records related to partner authentication or payment activities including request and response details, status, and audit information.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.id 
IS 'ID: Unique identifier for the partner transaction record.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.request_dtimes 
IS 'Request DateTimestamp: Date and time when the transaction request was initiated.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.response_dtimes 
IS 'Response DateTimestamp: Date and time when the transaction response was received.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.request_trn_id 
IS 'Request Transaction ID: Unique identifier for the request transaction generated by the system.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.auth_type_code 
IS 'Auth Type Code: Indicates the type of authentication used for the transaction.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.status_code 
IS 'Status Code: Indicates the status of the transaction (e.g., Success, Failed).';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.status_comment 
IS 'Status Comment: Detailed message describing the transaction result or failure reason.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.partner_id 
IS 'Partner ID: Unique identifier of the partner associated with the transaction.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.partner_name 
IS 'Partner Name: Name of the partner associated with the transaction.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.entry_type 
IS 'Entry Type: Indicates whether the transaction is credit or debit.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.amount 
IS 'Amount: Transaction amount associated with the partner transaction.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.cr_by 
IS 'Created By: ID or name of the user who created the transaction record.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.cr_dtimes 
IS 'Created DateTimestamp: Date and time when the record was created.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.upd_by 
IS 'Updated By: ID or name of the user who last updated the record.';
-- ddl-end --

COMMENT ON COLUMN pms.partners_transaction.upd_dtimes 
IS 'Updated DateTimestamp: Date and time when the record was last updated.';
-- ddl-end --